- source/position.cpp
PRETTY_JPをコメントアウトした際にUSI_PIECEが未定義でコンパイルエラーになるので、該当する文字列を直接書き込みました。
> 盤面を英字表示する際のコンパイルエラーを修正

- source/Makefile
Makefile内の王手将棋のソースファイル名が違っていてビルドが止まるのを修正、
ソースファイル名の後ろの空白がタブ混じりで一部のエディタで\の位置がずれるのを修正しました。
> Makefileにて王手将棋のソースファイル名が合っていないのを修正

- source/misc.cpp
- source/usi.cpp
stockfish由来のプロセッサーグループの設定ロジックを変更し、Intel Xeon Phi Processor 7250においてCPUを100%使い切れるよう変更しました。stockfish由来のロジックでは、全てのプロセッサーグルプに同数の論理プロセッサーが含まれることを仮定していますが、Intel Xeon Phi Processor 7250でWindows Server 2016を動かした場合、プロセッサーグルプ内の論理プロセッサーの数が64・64・64・64・16と不均一で、CPUを100%使い切ることが出来ませんでした。この問題を解決するため、先頭のプロセッサーグループから順に貪欲にスレッドIDを割り当てるよう変更しました。
よろしくお願いいたします。
> Intel Xeon Phi Processor 7250においてCPUを100%使い切れるようにした

- source/evaluate.h
EVAL_MATERIALでビルドするときPawnValueとfe_hand_endが定義されずコンパイルエラーになるので
EVAL_PPらと同じということにして処置しました
> 駒得評価関数での思考エンジンのコンパイルエラーを回避

- source/engine/mate-engine/mate-search.cpp
- source/extra/config.h
- source/extra/test_cmd.cpp
- source/usi.cpp
test_mate_engineコマンドを追加しました。
その他以下の細かい修正を加えてあります。
- 1手詰みルーチンで詰みを判定できない場合に不詰みと判定してしまうバグを修正した
- 探索ノード数のカウントにPositionの機能を使用するようにした
- パラメーター調整により一部の問題が解けるようになった
よろしくお願いいたします。
> 詰将棋エンジン用のテストコマンドを追加した

- source/extra/book/apery_book.cpp
- source/extra/book/apery_book.h
AperyBookのコンストラクタを複数回呼び出すと乱数未初期化のままhashを再生成しているので、
AperyBookを複数、もしくは複数回取り扱う際に支障になりそうです。
> AperyBook: 乱数初期化はinit()内で

- source/Makefile
msys2 上でのビルド設定にはスタック領域サイズの指定が無かったようなので、Makefileに追加してみました。linuxのbash上では `$ ulimit -s 16384` とか `$ ulimit -s unlimited` とかやるのが流儀なのかもしれないので（よくは知らない）、Windows環境にのみ指定しています。
ちなみに 100000000 の数字は、VisualC++のビルド設定から取りました。
- [V4.41時点での StackReserveSize](https://github.com/yaneurao/YaneuraOu/blob/02c9c583c9424fb6abf0e7c0772bfb013eef936e/source/YaneuraOu.vcxproj#L199)
- [現在の StackReserveSize](https://github.com/yaneurao/YaneuraOu/blob/0a0ca01936dfcebac8582efa831b77bf6d953c85/source/props/YaneuraOuSolution-release-x64.props#L42)
何でMakefileがShift-JISなのかなとは思いましたが、UTF-8にすると、UTF-8 without BOM (UTF-8N)ではなくUTF-8 with BOMに化ける危険があるからなのでしょうか。
> Makefile: stacksize 100000000 (only windows build)

- source/extra/all.h
- source/extra/kif_converter/kif_convert_tools.cpp
- source/extra/test_cmd.cpp
testコマンドの方にテスト絡みを実装してみました。
後手番でのKIF形式出力で、Pieceから手番情報を除き損ねていて、配列境界をはみ出していたので修正しました。
修正前:
```
$ ./msys2/2017Early/YaneuraOu-2017-early-clang-sse42 isready , position startpos moves 5i5h , test kifconvert , quit
info string created shared eval memory.
info string Eval Check Sum = 65cd7c55a9d4cd9 , Eval File = elmo(WCSC27)
readyok
position: lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B2K2R1/LNSG1GSNL w - 2
sfen: 1c1d 2c2d 3c3d 4c4d 5c5d 6c6d 7c7d 8c8d 9c9d 1a1b 9a9b 3a3b 3a4b 7a6b 7a7b 8b3b 8b4b 8b5b 8b6b 8b7b 8b9b 4a3b 4a4b 4a5b 5a4b 5a5b 5a6b 6a5b 6a6b 6a7b
csa: -1314FU -2324FU -3334FU -4344FU -5354FU -6364FU -7374FU -8384FU -9394FU -1112KY -9192KY -3132GI -3142GI -7162GI -7172GI -8232HI -8242HI -8252HI -8262HI -8272HI -8292HI -4132KI -4142KI -4152KI -5142OU -5152OU -5162OU -6152KI -6162KI …
```
> add "test kifconvert" , fix white turn convert to kif

- source/usi.cpp
GUIの「パス」入力（例: ShogiGUI）を受け入れる。
手番のみを変更した局面の検討を行いたい時、初期局面からの指し手の情報に null move を挟む事が考えられます。（ShogiGUIで「棋譜解析、検討モードで指し手をすべて送る」オプションを有効にし、パス `Ctrl+Alt+0` 入力する場合など）
例えば、以下のようなGUIからの局面・棋譜情報の入力が考えられます。
```
positon startpos 2g2f pass 5i6h
```
ShogiGUIの開発情報としては、以下のような仕様が挙げられています。
https://sites.google.com/site/shogixyz/home/shogigui/shogigui-kai-fa-qing-bao#TOC--
```
・投了はresignと記述する。
・勝ち宣言はwinと記述する。
・パス(null move)は0000（UCI方式)かpass(gpsfish方式）と記述する。
```
gpsfish の OpenShogiLib (OSL) 部分のソース (GPSfishでは `pass`)
http://gps.tanaka.ecc.u-tokyo.ac.jp/cgi-bin/viewvc.cgi/trunk/osl/core/osl/usi.cc?view=markup#230
```
if (str == "pass")
return Move::PASS(s.turn());
```
そのため、`0000`, `null`, `pass`  あたりの入力は null move として解釈した方が良いかと思います。
ただし、元となる Stockfish においては `position (startpos | <fen>) moves <fen>*` における null …
> accept gui null move

- source/extra/book/book.h
clangにてbuildに失敗しましたので報告します。
```
In file included from extra/book/book.cpp:2:
extra/book/book.h:122:26: error: extra qualification on member 'probe_impl'
bool BookMoveSelector::probe_impl(Position& rootPos, PRNG& prng, bool silent, Move& bestMove, Move& ponderMove);
~~~~~~~~~~~~~~~~~~^
```
> book.h: fix BookMoveSelector

- source/position.h
LOCAL_GAME_SERVER などで #define EVAL_NO_USE になる場合にビルドできなかったのを修正しました。
> LOCAL_GAME_SERVER などでビルドできなかったのを修正

- source/extra/kif_converter/kif_convert_consts.h
- source/extra/kif_converter/kif_convert_tools.cpp
- KIF形式の指し手出力でKI2型のSamePosFmtを指定し、後手番で「同成香」「同成桂」「同成銀」を指した場合、「同」の後に意図せず全角空白が入ってしまう？
- 未使用文字定数の全角/半角入力ミス
細かい修正ですが、一応念のため。
> kifconvert fix

- source/extra/kif_converter/kif_convert_consts.h
- source/extra/kif_converter/kif_convert_tools.cpp
- 文字列定数を `std::basic_string<charT>` から `charT *` に変更（バイナリサイズの低減）
- `to_sfen_string()` で `std::stringstream` オブジェクトにではなく `std::cout` に直接出力していた不具合の修正
> kifconvert wip20170719b

- source/shogi.h
- source/usi.cpp
GUI側で対応すべき所かは迷いどころですが、技巧をエンジンオプションで探索制限させて対局を行う人が一定数居るようですので、叩き台用に提案してみます。
- エンジンオプション `DepthLimit` , `NodesLimit` 追加
- `Option` の整数型を `int` から `long long` に型拡張 (`LLONG_MAX >= 9223372036854775807` とC++11規格で定義)
- エンジンオプション `EngineNuma` の最小値を `0` から `-1` に変更（`EngineNuma` のデフォルト値が `-1` だった）
> エンジンオプションによる探索制限

- source/eval/evaluate_kpp_kkpt.cpp
KPP KKPT評価関数をAVX2化するプルリクエストをさせていただきます。パフォーマンスプロファイラでホットスポットと判定されたdo_a_pc()とevaluateBody()をAVX2化しています。2ヶ所の変更で、計2.6%程度高速化しました。vgatherdd命令が使えないため、KPPT評価関数に比べ速度向上は小さくなっています。
> KPP KKPT評価関数のAVX2化

- source/eval/evaluate.cpp
評価関数のchecksumを追加しました。
* 真やねうら王
* リゼロepoch0～7
* 野生の読み太(20170626)
* 野生の読み太(20170802)
* elmo-qhapaq version 1.0
* elmo-qhapaq version 1.1
* relmo8
* yaselmo(20170705)
* KPP_KKPT型リゼロepoch4
また、誤字を修正しました。
> 各種評価関数のchecksumを追加

- source/eval/kppt/evaluate_kppt.cpp
sdt5のQhapaq_conflatedで使用した実装を整理したものです。
ここ数世代のCPUだと最大で5%ほど速度が上がるようです。Haswellなどでは1%程度しか速度が変わらないかと。
> evaluate_kpptの高速化

- .gitignore
- source/Makefile
- source/extra/book/book.cpp
- source/learn/learner.cpp
learner.cpp
教師データの変換器を実装しました。仕様の詳細は
http://qhapaq.hatenablog.com/entry/2017/12/25/002820
を参照してください。
book.cpp
BookIgnoreRate を追加
定跡の穴を見つける際に、一定の確率で定跡の手を不採択にする手が有効である（私調べ）
ので、やねうら王の標準機能にどうでしょう
.gitignore
Makefile
これらの変更は不要だと思います（此方のローカルの開発事情に起因してるので）
> Yane qhapaq

- jni/Android.mk
- jni/Application.mk
- script/linux_build.sh
- script/mingw_gcc.sh
- script/msys2_build.sh
- source/extra/bitop.h
- source/extra/config.h
各種環境のビルドものです。
- `script/msys2_build.sh`
MSYS2 64bit用バッチビルドスクリプトです。
g++ , clang++ でWindows用各種バイナリを `build/` 以下にバッチ生成します。
- `script/mingw_gcc.sh`
Linux (Ubuntu 18.04) mingw-w64 用バッチビルドスクリプトです。
g++ でWindows用各種バイナリを `build/` 以下にバッチ生成します。
- `script/linux_build.sh`
Linux (Ubuntu 18.04) 用バッチビルドスクリプトです。
g++8 , clang++-7 でLinux用各種バイナリを `build/` 以下にバッチ生成します。
- `jni/*.mk`
https://github.com/ai5/YaneuraOu/tree/android/ を元に作成しました。
Android NDK用ビルド設定です。Android arm64-v8a , x86_64 用バイナリを `libs/` 以下に生成します。
生成バイナリ例: https://github.com/mizar/YaneuraOu/releases/tag/v4.82-master%2B20180517.build2
ここで生成されたバイナリは、[ShogiDroid](http://shogidroid.siganus.com/)上での実行を想定しています。
Android NDK を導入、 `(Android SDKインストール先)\Sdk\ndk-bundle` などにPATHを通し、
シェル上で `YaneuraOu/` をカレントディレクトリとして、
`$ ndk-build …
> Buildfiles

- source/engine/mate-engine/mate-search.cpp
go mateコマンド実行時に探索が始まらないバグを修正しました。
よろしくお願いいたします。
> 探索が開始しないバグを修正した

- source/engine/mate-engine/mate-search.cpp
千日手のチェックを追加しました。
これにより一部の問題で大幅に高速化しました。
floodgate blogリンク | floodgateリンク | sfen | floodgate blog予測手数 | 変更前 (ms) | 変更後 (ms)
-- | -- | -- | -- | -- | --
http://b.kifupedia.org/20170430.html#p29 | http://wdoor.c.u-tokyo.ac.jp/shogi/view/index.cgi?csa=http://wdoor.c.u-tokyo.ac.jp/shogi/LATEST/2017/04/30/wdoor%2Bfloodgate-300-10F%2Bukamuse_6700K%2Bcatshogi%2B20170430143005.csa&move_to=102 | sfen l2g5/2s3g2/3k1p2p/P2pp2P1/1pP4s1/p1+B6/NP1P+nPS1P/K1G4+p1/L6NL b RBGNLPrs3p 1 | 33 | 2976 | 2856
http://b.kifupedia.org/20170430.html#p18 | http://wdoor.c.u-tokyo.ac.jp/shogi/view/index.cgi?csa=http://wdoor.c.u-tokyo.ac.jp/shogi/LATEST/2017/04/30/wdoor%2Bfloodgate-300-10F%2Bcoduck_pi2_600MHz_1c%2BShogiNet%2B20170430110007.csa&move_to=100 | sfen 6lnk/6+Rbl/2n4pp/7s1/1p2P2NP/p1P2PPP1/1P4GS1/6GK1/LNr5L b …
> Mate engine loop 2018 05 24

- source/learn/learner.cpp
学習時に omp_set_num_threads() を呼ぶタイミングの修正です。
OpenMP の実装に依存するのか、メインスレッドで呼んだだけでは設定が反映されない場合があるようです。
参考：
https://twitter.com/mktakizawa/status/1000644548995964928
https://software.intel.com/en-us/forums/intel-c-compiler/topic/494242
> Move omp_set_num_threads() call to worker threads

- source/engine/mate-engine/mate-search.cpp
詰手順を復元する探索ルーチンの中で
受け手側の手番かつ王手がかかっている状況で
1手詰みルーチンを呼び出しているバグを修正しました。
これにより金子清志氏の全応手逆王手最長１５手で
合法な詰手順が出力されるようになりました。
http://www.ne.jp/asahi/tetsu/toybox/challenge/c1090.htm
ただし、最短の詰手順ではありません。
> 詰み手順を復元する探索ルーチンの中で受け手側の手番かつ王手がかかっている状況で1手詰みルーチンを呼び出すバグを修正した

- source/engine/mate-engine/mate-search.cpp
逆王手がかかっている局面でnotimplementedを返さないようにするオプション、
ReturnNotImplementedIfCheckedを追加いたしました。
デフォルトはtrueで、falseにすると逆王手がかかっている局面でも探索を行います。
> 逆王手がかかっている局面でも詰みを探索するようにした

- source/engine/mate-engine/mate-search.cpp
異なる世代のキャッシュエントリを使用しないようにし、受け側の局面から探索させたあとに攻め側の局面から探索させると不詰と出力されるバグを修正しました。
よろしくお願いいたします。
> 詰将棋ルーチンで受け側の局面から探索させたあとに攻め側の局面から探索させると不詰と出力されるバグを修正した

- source/extra/bitop.h
```
In file included from jni/../source/bitboard.cpp:1:
In file included from jni/../source/bitboard.h:4:
In file included from jni/../source/types.h:17:
jni/../source/extra/bitop.h:292:24: error: no type named 'size_t' in
namespace 'std'; did you mean simply 'size_t'?
void deallocate(T* p, std::size_t n) { aligned_free(p); }
^~~~~~~~~~~
size_t
C:/Android/android-sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64\lib64\clang\8.0.2\include\stddef.h:62:23:
note: 'size_t' declared here
typedef __SIZE_TYPE__ size_t;
^
2 errors generated.
make: *** [obj/local/arm64-v8a/objs/tnk-mate-arm64-v8a/__/source/bitboard.o] Error 1
```
> - <cstddef> for std::size_t

- source/extra/book/makebook2019.cpp
`makebook think` コマンドでは `max_game_ply` なんてトークンは使えないよ、とエラーが出て `makebook endless_extend_tree` コマンドを正常に実行できない問題の修正です。
> - fix `makebook endless_extend_tree`

- source/engine/yaneuraou-engine/yaneuraou-search.cpp
参考: https://qiita.com/ak11/items/8bd5f2bb0f5b014143c8
go perft 4 あたりからノード数が一致しない問題。
そもそも、一部 LEGAL_ALL で指し手生成されてませんでした…。
> - `go perft <depth>` の探索修正

- source/engine/mate-engine/mate-search.cpp
MATE_ENGINE + FOR_TOURNAMENT の組み合わせでビルドエラーになる問題の修正です。
> - fix mate-engine + for-tournament

- source/config.h
ユーザーの思考エンジンがデフォルトの状態だとコンパイルできませんでした。
とりあえずEVAL_MATERIALにしておきました。
> - ユーザーの思考エンジンのコンパイルが通るように修正

- .github/workflows/make-mingw.yml
- .github/workflows/make-msys2.yml
- .github/workflows/make.yml
- .github/workflows/ndk.yml
- .github/workflows/release.yml
- jni/Android.mk
- jni/Application.mk
- script/android_build.ps1
- script/android_build.sh
- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/layers/clipped_relu.h
- source/eval/nnue/nnue_common.h
- source/eval/nnue/nnue_feature_transformer.h
- source/extra/bitop.h
- Android HalfKPE9ビルドの修正、他諸々
- 自動ビルドにおいて、gitレポジトリの展開先をカレントディレクトリから`./main`に変更
ShogiDroid向けHalfKPE9実行サンプル:
https://github.com/mizar/YaneuraOu/releases/download/v5.30-20201107c_androidfix/YOv5.30-Sylwi.zip
> - android build fix, and checkout path change to ./main

- script/bench.py
やねうら王エンジンのベンチマーク測定
```
usage: bench.py [-h] [--cmd CMD] [--loop LOOP] [--log LOG] engine1 eval1 [engine2] [eval2]
```
- python3 をインストールします。
- Windows 10 なら、例えば Microsoft Store から: https://www.microsoft.com/store/productId/9P7QFQMJRFP7
- 必要なら、 python3 の pip パッケージを更新します。
- `python3 -m pip install --upgrade pip`
- 必要なpythonパッケージをインストールします。（python3のインストール形態によっては管理者権限が必要な事があります）
- `python3 -m pip install cpuid pandas pexpect pyyaml statsmodels numpy==1.19.3`
- 実行例として、2つのエンジンと評価関数を使い、交互にベンチマークを行います。
- `python3 script/bench.py --cmd "16384 64 30 default time" --loop 10 /path/engine/original/Yaneuraou_NNUE-linux-clang++-10-tournament-ZEN2 /path/eval/original_NNUE/eval /path/engine/new/Yaneuraou_NNUE-linux-clang++-12-tournament-ZEN2 /path/eval/new_NNUE/eval`
- USI_Hash=16384 (16GB), Threads=64, …
> - bench.py

- script/msys2_build.ps1
- msys2_build.ps1 において、makeコマンドの実行優先度を実験用に `-n 0` (通常) に設定していたままだったので、これをniceのデフォルト（+10、実行優先度を下げる）に戻す
> - msys2_build.ps1 : nice value to default

- source/learn/learner.cpp
複数のプロセスでlearnコマンドを実行した場合、NUMAノード0しか使われなくなる事に気づきました。LearnerThink::calc_loss()はスレッド並列で動いており、それらのスレッドを適切なNUMAノードに割り当てることで、ある程度緩和できると考え、LearnerThink::calc_loss()内のワーカースレッドでWinProcGroup::bindThisThread()を呼び出すようにしました。
> LearnerThink::calc_loss()内のワーカースレッドでWinProcGroup::bindThisThread()を呼び出すようにした

- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/nnue_feature_transformer.h
- nnue_feature_transformer.h に関しては、AVX512対応とコード整理程度です。これによる性能向上は手元の環境ではありませんでした。
- affine_transform.h に関しては、ほぼ Stockfish NNUE ( https://github.com/official-stockfish/Stockfish/blob/7615e3485e75c2f1715d372f7bb1f546738a5c76/src/nnue/layers/affine_transform.h )の `Propagate()` 関数  そのままです。これにより、手元の環境では0.5%～1%程度の性能向上が見込まれます。
- それ以外は、単にインデントと名前空間の整理のみです。
engine1: 本patch適用前
engine2: 本patch適用後
```
2020-11-28 19:40:43,164 OS: Windows
2020-11-28 19:40:43,165
cmd: 16384 1 19 default depth
engine1: E:\shogi\dev\YaneuraOu-v5.32.0+20201128b.android-windows\windows\NNUE\YaneuraOu_NNUE-tournament-clang++-zen2.exe
engine2: E:\shogi\dev\20201128-pr_nnue-build-windows\windows\NNUE\YaneuraOu_NNUE-tournament-clang++-zen2.exe
eval1: D:\shogi\eval\tanuki2018_nnue
eval2: D:\shogi\eval\tanuki2018_nnue
log: …
```
> Backport from Stockfish NNUE

- source/YaneuraOu.vcxproj
必要な構成以外のビルドで依存しないライブラリ(OnnxRuntime, DirectML, openblas)を添付しないように。
> - vcxproj: 依存ライブラリ分離

- source/mate/mate_n_ply.cpp
MATE_ENGINE clang++ でのビルドの際に出る警告及びエラーの回避です。
```
mate/mate_n_ply.cpp:301:18: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 extension [-Wc++20-extensions]
found_mate = mated_even_ply<GEN_ALL>(pos, ply - 1) == MOVE_NONE /* 回避手がない == 詰み */;
^
mate/mate_n_ply.cpp:301:18: error: call to function 'mated_even_ply' that is neither visible in the template definition nor found by argument-dependent lookup
mate/mate_n_ply.cpp:326:38: note: in instantiation of function template specialization 'Mate::mate_odd_ply<true, false>' requested here
: (pos.in_check() ? mate_odd_ply<true,false>(pos, depth) : mate_odd_ply<false,false>(pos, depth));
^
mate/mate_n_ply.cpp:336:7: note: 'mated_even_ply' should be declared prior to the …
```
> - define templated mated_even_ply() : Avoid C++20 features

- source/extra/test_cmd.cpp
> test_cmd.cppにて、thread_numを上限としたfor文のカウンタにintを使用していたのをsize_tに変更（警告対応）

- source/eval/deep/nn_tensorrt.cpp
初期化されていない max_batch_size の値(0)を参照してメモリ確保していたため、NNTensorRT::forward() での評価の際にエラーを起こしていました。
> - fixed NNTensorRT::load() malloc with uninitialized size

- .editorconfig
- `*.props`: no insert final newline
- `Makefile`: 4 tab indent
- `*.mk`: 2 space indent
- `*.hpp`: 4 tab indent
> - .editorconfig

- script/bench.py
bench.py 実行時、エンジンオプションで PvInterval 0 を指定します。
実行画面への影響は特に無い部分ですが、
ファイルに出力されるログからPVをする時に役立つ場合もあるかと思います。
> - bench.py: PvInterval 0

- source/engine/dlshogi-engine/YaneuraOu_dlshogi_bridge.cpp
- source/eval/deep/nn_onnx_runtime.cpp
InterOpNumThreadsはグラフ全体のスレッド数（default値1）、
IntraOpNumThreadsはノード内の実行並列化の際のスレッド数設定（default値4）。
使用スレッドを変更したい時は IntraOpNumThreads の設定値を変更する。
InterOpNumThreads の効果はよく分からない。ORT_MKLでは効果無いかも。
cf: https://tadaoyamaoka.hatenablog.com/entry/2020/06/06/190259
TadaiYamaokaの日記 - 2020-06-06 - ONNX Runtimeを使ってみる その2(性能測定)
> なお、ONNX Runtimeのスレッド数の設定には、SetInterOpNumThreadsとSetIntraOpNumThreadsがあるが、前者はグラフ全体のスレッド数、後者はノード内の実行を並列化する際のスレッド数を設定する。
参考：https://github.com/microsoft/onnxruntime/issues/2177
SetInterOpNumThreadsの方も8に変えてみたが、処理時間に変化はなかった。
GPUを使わずCPUを使用する版で、使用するスレッド数を調節したいという要望に対応する事を目指したもので、ORT-MKLのビルドのみに影響があります。
開発環境のThreadripper3970Xの場合、本変更適用前のORT-MKLはおよそ64論理コア数の半分、32スレッド程度の使用率でした。
IntraOpNumThreads のオプション値を1に設定すれば、およそ1スレッド程度で動作、
IntraOpNumThreads …
> - ORT_MKL に エンジンオプション InterOpNumThreads, IntraOpNumThreads を追加。

- source/eval/deep/nn_tensorrt.cpp
複数GPU環境、TensorRT版ふかうら王において、1番目のGPUしか使われていなかった件の修正案です。
dlshogiの場合、 `UctSearch.cpp` 内で `cudaSetDevice()` が呼び出されていましたが、ふかうら王ではこの `cudaSetDevice()` を呼び出している箇所が無さそうでした。
https://github.com/TadaoYamaoka/DeepLearningShogi/blob/master/usi/UctSearch.cpp#L302-L339
手元の環境で `UCT_Threads1 3 , UCT_Threads2 3 , DNN_Batch_Size1 256` として複数GPUを使う設定を行うと、序盤の局面では複数GPUを使って dlshogi とほぼ同等の 100kNPS 程度の探索が出来そうです。
(ponder無しでのテスト対局)
> - TensorRT: cudaSetDevice()

- source/engine/dlshogi-engine/YaneuraOu_dlshogi_bridge.cpp
- source/eval/deep/nn.cpp
- source/eval/deep/nn.h
- source/eval/deep/nn_onnx_runtime.cpp
- source/eval/deep/nn_onnx_runtime.h
- source/eval/deep/nn_tensorrt.cpp
- source/eval/deep/nn_tensorrt.h
- source/props/YaneuraOuEdition-Deep-ORT-DML.props
- deep/nn : モデル読込中の gpu_id, batchsize を出力
出力する項目の追加。
- TensorRT : 存在しないCUDAデバイスを使おうとした時のエラー検知
cudaSetDevice() した時のエラー検知、これだけだと存在しないデバイスのスレッド数を設定した場合にエンジンがエラーで落ちるだけなので、後述のコミットで緩和を試みています。
- TensorRT : cudaFree() の際、一時的に cudaMalloc() したデバイスに変更する
https://github.com/yaneurao/YaneuraOu/commit/b2c38ec2f8d3b79f9e18ff3c76d2b70911533fc4 の補強、念の為、cudaFree()後に元のデバイスに戻るようにする。
- TensorRT: シリアライズ時、ファイル名に device_name, pci_bus_id を含める
gpu_idが同じデバイスがずっと同じデバイスとは限らないため、ファイル名に device_name, pci_bus_id を含めて混同の可能性を薄める。
- TensorRT : info string gpu_id , device_name , pci_bus_id
NNTensorRT::load_model() の際、gpu_id , device_name , pci_bus_id の情報を出力する。
- indent YaneuraOu_dlshogi_bridge.cpp
- deep : 対応デバイス数以上のIDに設定されたスレッド数を無視する
対応デバイスの数を検知し、デバイス数以上のIDに設定されたスレッド数を無視する事で、設定の食い違いによるエラー落ちを軽減する試み。 …
> deep: 複数デバイス検知周りの改善

- source/engine/dlshogi-engine/UctSearch.cpp
```
engine/dlshogi-engine/UctSearch.cpp: In member function 'void dlshogi::UctSearcher::ParallelUctSearch(const Position&)':engine/dlshogi-engine/UctSearch.cpp:361:55: error: no matching function for call to 'atomic_fetch_add(std::atomic<unsigned int>*, int)'
atomic_fetch_add(&search_limits.nodes_searched, 1);
^
```
> - g++ の一部バージョンで発生するエラーの回避

- .github/workflows/ndk.yml
- .github/workflows/release.yml
LTS 最新版が 2021-01 リリースの r21e ですので、アップデートしましょう。動作未確認ですが、ビルドが通るのは確認済みです。
本リポジトリの Android のビルドが失敗しているのは、一時的エラーで、この pull request とは無関係です。
> NDK のバージョンを r21e にする

- source/position.h
コンパイラの warning
```
warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
```
を減らします。
source/eval/nnue/nnue_common.h
source/learn/learner.cpp
での対応と統一感がちょっとないので、必要があれば、いずれかの形式に統一します。
source/engine/dlshogi-engine/UctSearch.cpp
は触っていません。
> Reduce warnings

- source/mate/mate_dfpn.hpp
df-pnの `select_the_best_child()` について、
2番目に小さいdn, pnを正しく計算できていないと思われます。
> - df-pnのsecond_pn,second_dnの計算が正しくない問題を修正

- .github/workflows/make.yml
Ubuntu20.04でのビルドテストにて、標準でインストール可能なclang++-11を使用するようにします。
> - switch main clang to clang-11

- source/engine/dlshogi-engine/dlshogi_searcher.cpp
- source/eval/deep/nn.cpp
特に、マルチGPU環境（Amazon EC2 p4d.24xlargeなど）において初期化処理の進行を分かりやすく表示します。
Amazon EC2 p4d.24xlarge の場合、GPU8個全てでモデル読み込みを終えるのにWCSC31の際には約90秒程度掛かっていたため、所要時間の情報表示は欲しいと思っています。
> - モデル読み込み時の情報表示追加

- source/engine/dlshogi-engine/dlshogi_searcher.cpp
engine/dlshogi-engine/dlshogi_searcher.cpp:643:4: warning: add explicit braces to avoid dangling else [-Wdangling-else]
else {
^
1 warning generated.
elseブロックを持つif文のすぐ外側で、中括弧を省略したif文を使用することはclang++にて警告が出るようです。
> - dangling-else

- source/book/apery_book.h
- source/book/book.cpp
- source/book/book.h
- source/book/makebook2015.cpp
read_apery_book() が read_book() の下請けになっていた経緯は多分無い？
https://github.com/yaneurao/YaneuraOu/pull/23/files?w=1
旧Apery形式定跡の読み書き拡張です。
Apery形式定跡の読み込みは、未登録の局面があってもその1手先に登録局面が無いか探索するように拡張しています。（そのため、処理に掛かる時間は大幅に増えています）
Apery形式定跡の書き出しにはZobristハッシュの初期化が必要であったため、 AperyBook::init() は public に変更しています。
> - r/w apery_book, AperyBook::init() to public

- .github/workflows/make.yml
Ubuntuでのビルドテスト環境において、以下の修正を行います。
- clang++-11でのビルドテストを削除。
- clang++-12のインストール時に、libomp-12-devを明示的にインストールするように変更。（明示的に指定しないとインストールされなくなったopenmpが必要なビルドテストに失敗していたため。）
- clang++-13でのビルドテストを追加。
> libomp-12-dev

- source/Makefile
tanuki- 2021-09-03 AMD Optimizing CPU Libraries 実験結果 - Google ドキュメント https://docs.google.com/document/d/1c-5VxR_TWH3okgTN28mZznPjdB06wxV13JfWNx7pCkU/edit
AMD Ryzen Threadripper 3990X を用いた場合、 OpenBLAS に比べ、 4% 程度学習が高速になりました。
> AMD Optimized BLISを使用するための変数を追加した

- jni/Android.mk
https://github.com/yaneurao/YaneuraOu/commit/55668c69154a73bfc2041c7db77efab85acc483c で漏れていた `jni/Android.mk` の修正案になります。
> - Android.mk: add source/testcmd/unit_test.cpp

- source/extra/bitop.h
#199 の関連イシューです。
AWSにはGraviton2というARM Neoverse N1系のプロセッサが存在します。
https://www.arm.com/why-arm/partner-ecosystem/aws
```
$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Model:               1
BogoMIPS:            243.75
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            32768K
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```
`g++` でコンパイルすると `extra/bitop.h:39:10: fatal error: mm_malloc.h: No such file or directory` というエラーが発生しました。
```
$ git diff Makefile
diff --git a/source/Makefile …
```
> g++ & arm64 でビルドできない問題を修正

- .github/workflows/make-deep-ubuntu.yml
- .github/workflows/make-mingw.yml
- .github/workflows/make-msys2.yml
- .github/workflows/make.yml
- .github/workflows/release.yml
- script/build.sh
- source/Makefile
- Graviton2 向けビルドテストを Ubuntu Linux 20.04 (amd64) 環境、 `aarch64-linux-gnu-g++-9` コンパイラにて行います。(`normal`, `tournament` target のみ)
- Graviton2 向けビルドオプションを `-mfpu=neon` から `-march=armv8.2-a+fp16+rcpc+dotprod+crypto` に変更します。（`-mfpu=neon` のままではビルドテストに失敗するため）
- 変更元: https://github.com/yaneurao/YaneuraOu/pull/201
- 参考: https://github.com/aws/aws-graviton-getting-started/blob/main/c-c++.md
- 参考: https://d1.awsstatic.com/webinars/jp/pdf/services/20200707_BlackBelt_Graviton2.pdf
- Ubuntu Linux 20.04 (amd64) 環境でのビルドテストに使うコンパイラの一部を変更します。 `clang++-13` → `clang++-14`
- 最新のclangで発生するwarning, error等を確認できるように。
- その他、ビルドマトリクスの整理など。
> - graviton2 build test

- .github/workflows/make-deep-ubuntu.yml
- CUDA Toolkit 11.5 Downloads : https://developer.nvidia.com/cuda-downloads
- NVIDIA CUDA Toolkit Release Notes : https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
CUDA Toolkit 11.5 のリリースに伴ってなのか、TensorRT版のビルドテストにおいてincludeファイルが見つからなくなるエラーが発生しているため、当面は `/usr/local/cuda/` ではなく、明示的に `/usr/local/cuda-11.4/` 以下を見るよう変更します。
> - cuda-11.4 の明示

- .github/workflows/make-msys2.yml
- .github/workflows/release.yml
https://twitter.com/msys2org/status/1451060685044129795
> Toolchain updates: clang/llvm 12.0.1 → 13.0.0 and gcc 10.3 → 11.2
msys2 toolchain の更新に伴い、 `ZEN3`, `AVXVNNI` を msys2 でのビルドテストおよびリリースビルドの対象に加えるよう変更します。
> - msys2 toolchain llvm-13, gcc-11.2 (add arch AVXVNNI, ZEN3)

- source/eval/deep/nn_tensorrt.cpp
- source/eval/deep/nn_tensorrt.h
`cudaStream_t stream` はこのPRではGPUごとに持っていますが、推論自体を並列に行いたい時は `context`, `stream`, `inputDims1`, `inputDims2`, `x1_dev`, `x2_dev`, `y1_dev`, `y2_dev` などは探索スレッドごとに持つように変更した方が良いかもしれません。（推測であり未確認）
参考:
ふかうら王 アピール文章
https://drive.google.com/open?id=1aO0gLSYvhph1uL_gaaohLYWTMpe1BdA8
> - TensorRT: 転送・推論を非同期に行う

- source/types.cpp
`operator<<(os, hand)` の出力先が `std::cout` になっていたので修正しました。
> - Handに対するoperator<<の出力先が正しくない問題を修正

- source/usi_option.cpp
start_logger()の引数がboolから`std::string`に変更されたが、WriteDebugLogオプションのデフォルト値が`false`のままだったため、デフォルトではデバッグログがファイル名`false`に常に書き出されていた。
https://github.com/yaneurao/YaneuraOu/commit/fa10bc3ad096c265041fbfe82f7259bcfc5aa680#diff-56d0745227250f49421f61a56de172b8b68624734977a6ff2c8f4a5fd67d0ba2L120-R131
> - `false` デバッグログファイルの抑止

- script/android_build.ps1
- script/android_build.sh
- script/build.sh
- script/mingw_gcc.sh
- script/msys2_build.ps1
- script/msys2_build.sh
- script/msys2_build32.sh
`EVAL_EMBEDDING=ON` のような、ソースファイルの構成が変化する追加オプションを指定した場合、ビルド用スクリプトファイルから `make clean` を呼び出す時にその指定が欠けていたため、前のビルドで使われたオブジェクトファイルが掃除し切れていないケースがありました。（自動ビルド以外のケースにおいて）
例えば、`EVAL_EMBEDDING=ON` 付きでコンパイラ `g++` , `clang++` の両方でビルドする際、前のビルドで作られた `embedded_nnue.o` が残っていたためにリンカエラーを起こす事がありました。（ソースファイルのコンパイル時、オブジェクトファイルに付与されるLTOのヒント情報が `g++`, `clang++` の間で互換性がないため。）
> - make clean $extra

- source/misc.cpp
OSXのファイルIO周りは初期から64ビットなので大丈夫です。
> OSXは初期から64ビットなので

- source/Makefile
DeepLearning for Ubuntu Linux のビルドが失敗していた件の修正です。
> - remove -lcublas

- YaneuraOu.sln
@nodchip さんの指摘より作成。
> PC に複数バージョンの VS がインストールされている環境で、 .sln に Visual Studio Selector を関連付けている場合、古いバージョンの VS で開かれるという問題がありそうです。
> VS2022 で .sln ファイルを開いたあと、開いている最中に .sln ファイルを削除し、 VS2022 の GUI 上ですべて保存をすると、 .sln ファイルがアップグレードされた状態で復活すると思います。
ついでですが、未使用と思われるターゲット(x86)の対応に誤りがあったので修正。
> - sln: vs2022

- .github/workflows/make-mingw.yml
- .github/workflows/make-msys2.yml
- .github/workflows/make.yml
- .github/workflows/release.yml
- script/build.sh
- script/mingw_gcc.sh
- script/msys2_build.ps1
- script/msys2_build.sh
- script/msys2_build32.sh
- ビルド周りの構成(VisualStudio向けのプロジェクト設定を除く)からgensfen周りを削除
- YANEURAOU_ENGINE_MATERIAL では代わりに evallearn ビルドを有効化
> - remove gensfen, enable evallearn on YANEURAOU_ENGINE_MATERIAL

- source/bitboard.h
clang++ でコンパイルすると以下のような警告が出力されます:
```
engine/yaneuraou-engine/../../bitboard.h:965:28: warning: '&' within '|' [-Wbitwise-op-parentheses]
return Bitboard((em ^ t) & mask | (~mocc & se), 0);
~~~~~~~~~^~~~~~ ~
engine/yaneuraou-engine/../../bitboard.h:965:28: note: place parentheses around the '&' expression to silence this warning
return Bitboard((em ^ t) & mask | (~mocc & se), 0);
^
(              )
engine/yaneuraou-engine/../../bitboard.h:982:31: warning: '&' within '|' [-Wbitwise-op-parentheses]
return Bitboard(0, (em ^ t) & mask | (~mocc & se));
~~~~~~~~~^~~~~~ ~
engine/yaneuraou-engine/../../bitboard.h:982:31: note: place parentheses around the '&' expression to silence this warning
return Bitboard(0, (em ^ t) & mask | (~mocc & se));
^
(              )
```
この PR ではそれに対処します。
> Deal with `-Wbitwise-op-parentheses`

- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/nnue_feature_transformer.h
Stockfish の
- https://github.com/official-stockfish/Stockfish/commit/564456a6a824bfca26d6d9af5b35a055eb9fc6c2
- https://github.com/official-stockfish/Stockfish/commit/2c36d1e7e7374b8babb3cc503c0bc07ceb83dbf8
をマージするためのプルリクエストです。 nps は変更前と変更後で以下のように変化しています。
変更前
```
===========================
Total time (ms) : 60004
Nodes searched  : 77916762
Nodes_searched/second    : 1298526
===========================
===========================
Total time (ms) : 60029
Nodes searched  : 78165853
Nodes_searched/second    : 1302134
===========================
===========================
Total time (ms) : 60006
Nodes searched  : 78021690
Nodes_searched/second    : 1300231
===========================
```
変更後
```
===========================
Total time (ms) : 60008
Nodes searched  : 77163881 …
```
> Fix overflow in add_dpbusd_epi32x2

- source/extra/bitop.h
インデックスを返すために最後に-1しないといけませんが、それが抜けています。
> emulation版のMSB32/64 で-1をし忘れている

- source/bitboard.cpp
- source/types.cpp
- source/types.h
- d1 ? d1 == Effect8::directions_of(sq2, sq3) : falseをd1 && d1 == Effect8::directions_of(sq2, sq3)に式を簡略化。
- std::string((pc & 32) ? "D":"") ではstring型にする必要はないため、(pc & 32) ? "D":""に変更。
- FOUND:;の不要なセミコロンを削除。
- 空白やインデントを微調整。
> types.hとtypes.cppで冗長なコードを整理し、空白やインデントを微調整

- source/bitboard.cpp
- source/movegen.cpp
bitboard.cppの方向利きのUnitTestにおいて
```cpp
all_ok = ...
```
と書かれていた箇所があったため、
```cpp
all_ok &= ...
```
に修正し、修正後もUnitTestが通ることを確認しました。
> 方向利きのUnitTestで`all_ok &=`の代わりに`all_ok =`になっていたのを修正

- source/eval/nnue/layers/clipped_relu.h
`ClippedReLU::Propagate`でAVX-512が有効な場合の実装を行いました。
halfkp_512x2-8-96のようなアーキテクチャの場合に、AVX-512で処理すると端数が生じ、その分速度が低下したため`kInputDimensions`の値に合わせてフォールバックするようにしました。
こちらの環境 (R9-7945HX) では (変更前でも変更後でも) AVX-512を有効にするとNPSが若干低下するため、この変更による速度向上については計測できていません。
> ClippedReluのAVX-512対応を実装

- source/eval/nnue/architectures/halfkp_1024x2-8-32.h
- source/eval/nnue/architectures/halfkp_1024x2-8-64.h
- source/eval/nnue/architectures/halfkp_256x2-32-32.h
- source/eval/nnue/architectures/halfkp_512x2-16-32.h
- source/eval/nnue/architectures/halfkpe9_256x2-32-32.h
- source/eval/nnue/architectures/halfkpvm_256x2-32-32.h
- source/eval/nnue/architectures/kp_256x2-32-32.h
- source/eval/nnue/architectures/nnue_arch_gen.py
- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/layers/affine_transform_sparse_input.h
- source/eval/nnue/layers/simd.h
`Stockfish17`の`AffineTransform`と`AffineTransformSpraseInput`を移植してきました。
探索depth固定でのbenchコマンドのノード数も変化しておらず(AVX2やAVX-512では)、正しく動作しているようです。
SSE4.2以下や、NEONについてはこちらでは検証できておりません。
R9-7945HXでAVX-512有効の場合、標準NNUEでは移植してきた`AffineTransform`を使うことで9.2%、さらに`AffineTransformSparseInput`を使うことで10.7%ほどNPSが向上することが確認できました。
ただし、`halfkp_512x2-8-64`や`halfkp_512x2-8-96`ではNPSの低下が確認されています。
> Stockfish17のAffineTransformとAffineTransformSparseInputを移植した

- source/Makefile
- source/eval/nnue/layers/affine_transform_sparse_input.h
- source/eval/nnue/layers/simd.h
変更後も変更前も (現状は) 常に偽であることは変わりはないですが、Stockfishのようにvnni256に対応したときのために修正しておきました。
> ifdefの条件を修正した

- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/layers/affine_transform_sparse_input.h
Stockfishから`AffineTransformSparseInput`を持ってきたときに、`kOutputDimensions`が4で割り切れない場合の処理を書いていなかったので、HalfKP 1536x2-15-32 などが正常に動作しない問題があり、それを修正しました。SIMD化していないので遅いです。
> `kOutputDimensions`が4で割り切れない場合の処理がなかったので追加。

- source/eval/nnue/layers/affine_transform.h
- source/eval/nnue/layers/affine_transform_sparse_input.h
AVX2以上を扱えるCPUでもSSE2を使わないといけないのは少しもったいない気がしたので、AVX2とAVX-512の実装もしました。
SIMDについて詳しくないので、速い書き方なのかどうかなどはわかりませんが、AVX2、AVX-512のどちらも正しく動作することは確認しました。
> AffineTransformで`kOutputDimensions`が4で割り切れない場合でもAVX2やAVX-512を使えるようにした。

- source/bitboard.h
> 最下位ビット以外が1になる場合があるバグ修正
