source/engine/local-game-server/local-game-server.cpp

思考エンジンのプロセスを終了時に待機するようにしました
タイムアウトした場合はTeminateProcess()で強制終了させるようにしています。
また思考エンジンのスレッドのハンドルがリークしていたため閉じるようにしました。

思考エンジンの終了を待機するようにした

---

script/engine_invoker5.py

変更点
- コマンドラインオプションのパースにargparseを使用するようにした
リファクタリング変更をPull Requestさせていただきます。
よろしくお願いいたします。

リファクタリング: コマンドラインオプションのパースにargparseを使用するようにした

---

script/engine_invoker5.py

変更点
- パスの結合をos.path.join()で行うようにした
Pull Requestさせていただきます。
よろしくお願いします。

リファクタリング: パスの結合をos.path.join()で行うようにした

---

source/engine/2017-early-engine/2017-early-search.cpp

定跡データベースの採択率に比例して指し手を選択するオプションConsiderBookMoveCountを追加しました。

定跡データベースの採択率に比例して指し手を選択するオプション

---

source/props/YaneuraOuEdition-2016Late.props
source/props/YaneuraOuEdition-2016Mid.props
source/props/YaneuraOuEdition-2017Early.props
source/props/YaneuraOuEdition-2017Goku.props
source/props/YaneuraOuEdition-CheckShogi.props
source/props/YaneuraOuEdition-MustCapture.props
source/props/YaneuraOuEdition-classic-tce.props
source/props/YaneuraOuEdition-classic.props
source/props/YaneuraOuEdition-help-mate.props
source/props/YaneuraOuEdition-local-server.props
source/props/YaneuraOuEdition-mate.props
source/props/YaneuraOuEdition-mini.props
source/props/YaneuraOuEdition-nano-plus.props
source/props/YaneuraOuEdition-nano.props
source/props/YaneuraOuEdition-random.props
source/props/YaneuraOuEdition-user.props

各エディションの設定にNDEBUGの指定が紛れていたので除去。

sources/props/YaneuraOuEdition-*.props: remove NDEBUG

---

YaneuraOu.sln
source/YaneuraOu.vcxproj

`Debug-mate|x86` が `props\YaneuraOuEdition-2017Early.props` のままだったので一応。

props: add target for -mate and -user

---

source/extra/kif_converter/kif_convert_consts.h
source/extra/kif_converter/kif_convert_tools.cpp
source/extra/kif_converter/kif_convert_tools.h

kifconv consts, utf8/16/32 string

---

source/extra/kif_converter/kif_convert_tools.cpp

error, warningsが出ていたので取り敢えずfixを上げておきます。

move_strike > move_drop 修正漏れ直し, fix assert

---

source/extra/book/book.cpp

BookOnTheFlyの機能が壊れていたようなので修正しました。

book.cpp: fix BookOnTheFly mode

---

source/extra/kif_converter/kif_convert_consts.h
source/extra/kif_converter/kif_convert_tools.cpp
source/extra/kif_converter/kif_convert_tools.h
source/extra/test_cmd.cpp

- 文字列定数の複数形式へのマクロ・テンプレート展開
- 文字列定数と共に文字幅情報を保持
- マス目の書式設定の他に、手番文字・同～の書式設定を追加
- CSA,KIF,KIF2形式の棋譜出力を追加 (SFEN形式もおまけで追加しましたがstd::string型の棋譜出力のみ)
などを行ってみました。
```
$ ../source/YaneuraOu-by-gcc.exe bookfile no_book , isready , position sfen 1nsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1 moves 8c8d 7g7f 8d8e 8h7g 7a6b 9g9f 5a4b 9f9e 3c3d 7i7h 4b3b 7g2b+ 3a2b 7h7g 2b3c 2h6h 8b8d 5i4h 6a5b 4h3h 3d3e 4i4h 7c7d 3i2h 6b7c 6h8h 7c6d 8g8f 8a7c 8f8e 8d8e 7g8f 8e8a 9e9d P*8g 8h8g 6d6e P*8b 8a8b P*8e 6e7f 8g8h 9c9d 9i9d 7c6e 9d9c+ 8b8a 9c9b B*9f 6i5h 7f8g+ 8h6h 8g7h 6h7h 9f7h+ 9b8a R*8h R*7a 8h8f+ B*5f 5b4b 5f6e 8f8i 2h3i 7h6i S*4i 8i8e 6e7d 8e7f 7d6c+ 7f7a 8a7a P*6f 6c8e P*7g R*7b 7g7h+ N*6d R*2d 7b6b+ 7h6h 7a6a 4a3a 6d5b+ 6f6g+ 5h6g 6h6g 1g1f 6i8g 3i2h P*7d 8e6g 8g5d 6a5a P*6a 6b6a S*7b …
```

kifconvert

---

source/usi.cpp

Optionの値チェック部分での文字列数値変換を64bit化し忘れていました。

option value check: stoi() -> stoll()

---

source/eval/nnue/layers/affine_transform.h
source/eval/nnue/layers/clipped_relu.h
source/eval/nnue/nnue_common.h
source/eval/nnue/nnue_feature_transformer.h

NNUE 評価関数に NEON 命令対応のコードを追加しました。

Support NEON for NNUE evaluation functions

---

source/engine/mate-engine/mate-search.cpp

現在の実装より平均的に長い詰み手順を返すMorePreciseMatePvオプションを追加しました。
df-pn探索ルーチンが探索したノードの中で、攻め側から見て最短、受け側から見て最長の手順を返します。
df-pn探索ルーチンが詰将棋の詰み手順として正規の手順を探索していない場合、
詰将棋として正しい詰み手順を出力する保証はありません。
例えば以下の17手詰めの詰将棋に対し、本ルーチンは19手の手順を返します。
http://www005.upp.so-net.ne.jp/tsumepara/contents/4appre/kanju/kanju13.htm
checkmate L*6h 7h6h N*5h 4h5h N*7h 6h7h L*6i 5h6i L*6h 5i6h N*5h 5g5h+ L*6g 5h6g 4g6g 6f6g 8g7f 6g5g R*6g

より長い詰み手順を返すMorePreciseMatePvオプションを追加した

---

source/engine/mate-engine/mate-search.cpp

詰将棋エンジンで制限時間をチェックするようにいたしました。
GUIからエンジンへ制限時間を設定した上で詰将棋エンジンを解かせる場合は、
USIプロトコル通り
> go checkmate 60000
などと指定してください。
制限時間を越えた場合、USIプロトロルにある通り、エンジンからは
> checkmate timeout
が返ってくるようになっています。
よろしくお願いいたします。
将棋所：USIプロトコルとは http://www.geocities.jp/shogidokoro/usi.html

詰将棋エンジンで制限時間をチェックするようにした

---

source/engine/mate-engine/mate-search.cpp

clang++でコンパイルした際のwarningを消しました。
よろしくお願いいたします。

コンパイル時のwarningを消した

---

source/engine/mate-engine/mate-search.cpp

置換表エントリの世代を削除し、置換表エントリのハッシュの最下位ビットに探索開始局面の手番を入れるようにした。これにより256回以上詰将棋ルーチンを呼び出した場合に、開始局面の手番の関係で置換表の意図しない結果が取得されてしまう問題を修正いたしました。

置換表エントリの世代を削除し、置換表エントリのハッシュの最下位ビットに探索開始局面の手番を入れるようにした

---

source/engine/mate-engine/mate-search.cpp

clang++によるコンパイル警告を抑制した

---

source/engine/mate-engine/mate-search.cpp

詰探索中の出力方法を変更しました。
- 一定時間ごとに探索ノード数、探索時間、nps、置換表使用率を出力するようにした
- 探索終了時に探索ノード数、探索時間、nps、置換表使用率を出力するようにした
よろしくお願いいたします。

詰探索中の出力を変更した

---

.github/workflows/release.yml

- 頭文字が "v*" にマッチする tag をpushした時に自動で作成する release において、zip/7z書庫に source/ 以下のファイルを追加する

- release archive: add source

---

.github/workflows/release.yml

- 頭文字が "v*" にマッチする tag をpushした時に自動で作成する release において、本文テキストのtypoを修正

- release.yml: SSE3 -> SSSE3

---

jni/Android.mk

- https://github.com/mizar/YaneuraOu/actions/runs/388329926
- https://github.com/mizar/YaneuraOu/actions/runs/388317331
Android用Makefileの修正です。

- Android.mk

---

.editorconfig
source/YaneuraOu.vcxproj
source/YaneuraOu.vcxproj.filters

- 拡張子毎のカスタムエディタ設定ファイル
cf. https://docs.microsoft.com/ja-jp/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019
- VisualStudio用プロジェクトファイルに幾つかのファイルを追加登録

- add .editorconfig

---

source/eval/nnue/layers/affine_transform.h

cf. https://github.com/official-stockfish/Stockfish/commit/d862ba40692797031ec5b0d95e46bcfc5a80f06c
手元の環境では、1スレッドdepth19では約+1.5%
64スレッド30秒では約+0.5%の速度向上でした。

- Stockfish PR#3254, PR#3261

---

README.md

https://github.com/yaneurao/YaneuraOu/pull/149 依存
README.md への DeepLearning CI ビルド結果バッジの表示部分です。

- badge for DeepLearning CI

---

source/eval/nnue/trainer/trainer_feature_transformer.h

- Trainer<FeatureTransformer>::Propagate()
- Trainer<FeatureTransformer>::Backpropagate()
- Trainer<FeatureTransformer>::QuantizeParameters()
の OpenMP を使用している部分で、 WinProcGroup::bindThisThread() を呼び出すよう変更しました。
よろしくお願いいたします。

NNUE評価関数学習時、Windows環境下でCPUが2つある場合に、論理64コアに負荷が集中する問題を修正した

---

.github/workflows/make.yml

Add development packages
Fixes: #168

[#168] Build script

---

.github/workflows/make-msys2.yml
.github/workflows/release.yml
script/msys2_build.ps1
script/msys2_build.sh
script/msys2_build32.sh

cf. https://github.com/msys2/MSYS2-packages/commit/0235754b07cbf708d28841aa59c0eddbe5ddd7a7

- msys2: `pactoys-git` -> `pactoys`

---

source/bitboard.cpp

https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_cmpeq_epi64&ig_expand=4268,4268,900,900&techs=SSE4_1

- USE_SSE41 for _mm_add_epi64

---

README.md

クリックしたらbadgeの画像が開くのを修正しました
リンク先もpushに限定した方がいいかもしれないけどとりあえずこれで

README.mdのbadgeにリンク追加

---

source/Makefile

MakefileにApple M1用のビルドターゲットCPUオプションを追加

Apple M1用のビルドターゲット

---

.github/workflows/release.yml

Google Driveでの、たややんさんによる水匠5の元ファイル配布が終了していた事に対する対応です。

- suisho5 embedded_nnue resource

---

source/YaneuraOu.vcxproj

Debug-Deep-TensorRT が https://github.com/yaneurao/YaneuraOu/compare/master...mizar:pr_vcxproj?expand=1#diff-9136f3effb31338b44c35ebfc574bfb9b49ca08d07af1f701eae07acc0a6f071L393-L398 とで重複して定義されていたので、片方を削除しました。

- remove duplicate Debug-Deep-TensorRT

---

source/eval/deep/nn_onnx_runtime.cpp

- ORT model filename

---

jni/Android.mk

- Android: yo_cluster

---

.github/workflows/make-macos.yml
.github/workflows/release.yml
.gitignore
jni/Android.mk

- .gitignore 対象の整理
- yo-cluster 関連ソースを Android Makefile に追加
- YANEURAOU_ENGINE_DEEP_COREML / FukauraOu_CoreML を自動ビルド対象に追加

workflows: CoreML

---

source/usi.cpp

Fix compile error

---

.github/workflows/make-wasm.yml
.github/workflows/release.yml
script/wasm_build.cmd
script/wasm_build.sh
script/wasm_docker_build.js

As mentioned here https://github.com/yaneurao/YaneuraOu/pull/265.
First I tried 3.1.47, which built fine, but didn't work in browser. So I endep using 3.1.43, which is what was last used. Tested k-p build.

Use emsdk:3.1.43 not emsdk:latest

---

source/position.cpp

最終的にsilver / gold effectでandを取るのでここでは不要です。

不要なandをコメントアウト

---

source/YaneuraOu.vcxproj
source/YaneuraOu.vcxproj.filters

SotckfishからAffineTransformを移植してきた際に、プロジェクトファイルに追加し忘れていたのを修正しておきました。

プロジェクトファイルに不足ファイルを追加

---

source/engine/yaneuraou-engine/yaneuraou-search.cpp

PvNodeで宣言勝ちのチェックを行うように修正

---

source/eval/nnue/architectures/nnue_arch_gen.py

出力ファイル存在時のwarningメッセージを修正
